<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DAREDEVIL" ignored="1" name="Default test(failed)" tests="1" failures="1" timestamp="2023-09-16T20:18:14 IST" time="0.047" errors="0">
  <testcase name="validateTitle" time="0.006" classname="testNGTestcases.RetryFailedTCAtRuntime">
    <failure type="java.lang.AssertionError" message="Expected result is not met">
      <![CDATA[java.lang.AssertionError: Expected result is not met
at testNGTestcases.RetryFailedTCAtRuntime.validateTitle(RetryFailedTCAtRuntime.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at testNGTestcases.RerunFailedTCsFromClass.main(RerunFailedTCsFromClass.java:20)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- validateTitle -->
  <testcase name="doLogin" time="0.0" classname="testNGTestcases.RetryFailedTCAtRuntime">
    <ignored/>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Default test(failed) -->
